#!/bin/bash

feh --bg-scale ~/pics/redtrees.jpg

#unclutter -root -idle 3 &

# disable for now, weirds out urxvt caret and doesn't work properly with opacity
#xcompmgr &

xrdb -merge ~/.Xresources

# switch esc with caps lock
xmodmap ~/.xmodmaprc

# ck-launch-session dbus-launch needed nm-applet permissions
#exec ck-launch-session dbus-launch --exit-with-session ~/.launchwm
exec ~/.launchwm
#exec ~/.cabal/bin/xmonad
